apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  namespace: web-namespace
  label:
    app: my-k8s-application
spec: 
# Для решения проблемы мультизональности кластера был выбран Shipper оператор для поставки на несколько кластеров
# Способ довольно ограниченный но выбран для большей отказоустойчивости деплоймента
  revisionHistoryLimit: 3
  template:
    chart:
      name: nginx
      repoUrl: https://storage.googleapis.com/shipper-demo
      version: 0.0.1
    clusterRequirements:
      regions:
        - name: local
          strategy:
      steps:
        - capacity:
            contender: 1
            incumbent: 100
          name: staging
          traffic:
            contender: 0
            incumbent: 100
        - capacity:
            contender: 100
            incumbent: 0
          name: full on
          traffic:
            contender: 100
            incumbent: 0
    values:
      replicaCount: 3
  selector:
    matchLabeles:
      project: hello
  template:
    metadata:
      label:
        project: hello
    spec:
      containers:
        - name: 
          image:
          ports:
            - containerPort: 80
  
