#---------------------------------
# Manifest file to create for test company Mindbox
# by Prytkov Sem github: coykies   
#---------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  label:
    app  : my-k8s-application
    env  : production-ready
    owner: PrytkovSem
spec: 
  replicas: 4 # run 4 pods
  selector:
    matchLabeles:
      project: mindbox
  template:
    metadata:
      label:
        project: mindbox
    spec:
      containers:
        - name : mindbox-app
          image: nginx:latest
          ports:
            - containerPort: 80
  


